name             'grailsapp'
maintainer       'Eric Helgeson'
maintainer_email 'erichelgeson@gmail.com'
license          'all_rights'
description      'Installs/Configures a grailsapp'
long_description 'Installs/Configures a grailsapp'
version          '0.1.0'

depends 'java'
depends 'sysdig'
depends 'selinux_policy'
depends 'firewall'
